import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "shadcn/ui Sample App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body>{children}</body>
    </html>
  );
}
